{% set name = "ndarray" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ndarray/ndarray/archive/{{ version }}.tar.gz
  sha256: 106fbeaab28f7e18d3458df823a6553090cb0ea8c7ef8a282580267219a27dcc
  patches:
    - linux-aarch64.patch  # [aarch64]

build:
  number: 1
  skip: true  # [win]
  ignore_run_exports_from:
    - numpy *
    - pybind11

requirements:
  build:
    - cmake
    - m4
    - {{ compiler('cxx') }}
    - pkg-config
    - make

  host:
    - boost-cpp
    - fftw
    - eigen
    # following are test dependencies
    - numpy *            # [build_platform == target_platform]
    - pybind11 >2.2      # [build_platform == target_platform]

test:
  commands:
    - test -f ${PREFIX}/include/ndarray.h  # [unix]
    - test -f ${PREFIX}/include/ndarray/ArrayBaseN.h  # [unix]
    - test -f ${PREFIX}/include/ndarray/detail/Core.h  # [unix]

about:
  home: https://github.com/ndarray/ndarray/
  doc_url: https://ndarray.github.io/ndarray/
  dev_url: https://github.com/ndarray/ndarray/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: NumPy-friendly multidimensional arrays in C++
  description: |
    ndarray is a template library that provides multidimensional array objects in C++, with an
    interface and features designed to mimic the Python 'numpy' package as much as possible.

extra:
  recipe-maintainers:
    - mwittgen
    - brianv0
    - TallJimbo
