{% set name = "ndarray" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ndarray/ndarray/archive/{{ version }}.tar.gz
  sha256: adf13e40735572d391de0a3836aa04319b7d780def8e159b03c34decfa6703c0
  patches:
    - 0001-shared-unit-test-link.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - m4
    - {{ compiler('cxx') }}
    - pkgconfig

  host:
    - boost
    - fftw
    - numpy
    - pybind11 >2.2
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/ndarray.h  # [unix]
    - test -f ${PREFIX}/include/ndarray/ArrayBaseN.h  # [unix]
    - test -f ${PREFIX}/include/ndarray/detail/Core.h  # [unix]

about:
  home: https://github.com/ndarray/ndarray/
  doc_url: https://ndarray.github.io/ndarray/
  dev_url: https://github.com/ndarray/ndarray/
  license: BSD
  license_file: LICENSE
  summary: NumPy-friendly multidimensional arrays in C++
  description: |
    ndarray is a template library that provides multidimensional array objects in C++, with an 
    interface and features designed to mimic the Python 'numpy' package as much as possible.

extra:
  recipe-maintainers:
    - brianv0
    - TallJimbo
