travis:
  secure:
    BINSTAR_TOKEN: SfNUMknDnsj+2OX/3K3kei/VYPfYyBufM3AN4SEV6U+OC1ewVevzhhI3oedZJ/QSXsnwJOGXJ/pqsUayCuRy0vrD5N1L4TSt3O4twrJW3Qt3S1lruh/BCQ3c/j0LAalDuKCBHbEQUy7ocrWqdexTJMZoEkdia+rJVUbuV9KYV/yJwicnBJ8NSMTshHM++ykwUzUiHCJ1H2irFwhgw7B/HoVQF5hTumSD7YtBdmx5P6wf4griBft8SO/A7klgBSdaqAkqhucyV0AZJrgxJuAcukOVWfvEBxXXkSMxPIv8EIbqq2e2JnMS1yMwzK5bkApZoTij3EyaYYmZFDPIqA/n1ymRCJlFewYgjXurhlJTGeTeUTpXqIAWdCUaBzggZ1hEwgR6fdHiLbEea/kxrMCjkvR28L2Xyr/fjl5QlKy/YV4WxT2X7/QFfixJ/OrO7TC71FzLoHHFIZeeVhHhIuuJK2HuC/bA7OkWCeVMh1vcdT4BfP6618WMjH8AvsBWKePQazELFRDc32RjLCtDaXaop3hJ9lmRlY0A+S9l5tXy8mrJQbhRZcZcDumolHWRzaF7kpNaRJhhDDP7TpV/NATQRtnJBNf52eFbwO4UeUwMvfXEI4rDSLm9a36DF3jKiWooWBMTSdyibLxdEKpFMrfGr3GHAJtKhRUX9IsVvtyQYqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
